<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '企业介绍';
$typeArr[3] = '企业文化';
$typeArr[4] = '发展历程';
$typeArr[5] = '服务项目';
$typeArr[6] = '摄影师';
$typeArr[7] = '场景布置';
$typeArr[8] = '新娘妆';
$typeArr[9] = '展会庆典';
$typeArr[10] = '乐会';
$typeArr[11] = '婚礼视频';
$typeArr[12] = '案例展示';
$typeArr[13] = '分类一';
$typeArr[14] = '分类二';
$typeArr[15] = '分类三';
$typeArr[16] = '设备展示';
$typeArr[17] = '新闻资讯';
$typeArr[18] = '行业新闻';
$typeArr[19] = '公司新闻';
$typeArr[20] = '网站公告';
$typeArr[21] = '人才招聘';
$typeArr[22] = '联系我们';
$typeArr[23] = '分类一';
$typeArr[24] = '分类二';
$typeArr[25] = '分类三';
?>