<div class="hrBox">
    <div class="hrBoxL">
      <ul>
        <li><span>所需职位：</span></li>
        <li class="bgWhite">所需人数：</li>
        <li class="haode">具体要求：</li>
      </ul>
      <div class="clear"></div>
    </div>
    <div class="hrBoxR">
      <ul>
        <li class="topline"><span class="fl">[field:title/]</span><a href="http://wpa.qq.com/msgrd?v=3&uin=6009709&site=qq&menu=yes" class="fr" title="应聘此职位"><img src="/skin/images/re.gif" width="90" height="26" /></a>
          <div class="clear"></div>
        </li>
        <li class="bgWhite">[field:renshu/]
          <div class="clear"></div>
        </li>
        <li class="haode">
		[field:body/]
		</li>
      </ul>
      <div class="clear"></div>
    </div>
  </div>