<?php
$z[0]=Array("field","",345,364);
$z[0][4]['name']="title";
$z[1]=Array("global","",365,391);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",987,1024);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1258,1287);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1429,1448);
$z[4][4]['name']="title";
$z[5]=Array("field","",1466,1484);
$z[5][4]['name']="body";
$z[6]=Array("prenext","",1509,1537);
$z[6][4]['get']="preimg";
$z[7]=Array("prenext","",1543,1572);
$z[7][4]['get']="nextimg";
$z[8]=Array("type","<a href=\"list.php?tid=[field:id/]\" title=\"返回列表\" class=\"back\">返回列表</a>",1578,1703);
$z[8][4]['typeid']="0";
$z[8][4]['row']="1";
$z[9]=Array("include","",1750,1789);
$z[9][4]['filename']="footer_m.htm";

?>