<?php
$z[0]=Array("field","",298,317);
$z[0][4]['name']="title";
$z[1]=Array("global","",318,344);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1492,1527);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1757,1786);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n  <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a><span>|</span>\r\n  ",1881,2034);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[5]=Array("field","",2108,2127);
$z[5][4]['name']="title";
$z[6]=Array("field","",2160,2212);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('Y/m/d',@me)";
$z[7]=Array("field","",2240,2267);
$z[7][4]['name']="phpurl";
$z[8]=Array("field","",2291,2314);
$z[8][4]['name']="id";
$z[9]=Array("field","",2319,2343);
$z[9][4]['name']="mid";
$z[10]=Array("field","",2454,2472);
$z[10][4]['name']="body";
$z[11]=Array("prenext","",2581,2606);
$z[11][4]['get']="pre";
$z[12]=Array("prenext","",2633,2659);
$z[12][4]['get']="next";
$z[13]=Array("type","<a href=\"[field:typelink /]\" title=\"返回列表\" class=\"back\">[返回列表]</a>",2671,2792);
$z[13][4]['typeid']="0";
$z[13][4]['row']="1";
$z[14]=Array("include","",2819,2856);
$z[14][4]['filename']="footer.htm";

?>