<?php
$z[0]=Array("field","",345,364);
$z[0][4]['name']="title";
$z[1]=Array("global","",365,391);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",987,1024);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1258,1287);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n        <li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span> </li>\r\n        ",1518,1732);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[5]=Array("field","",1829,1848);
$z[5][4]['name']="title";
$z[6]=Array("field","",1866,1884);
$z[6][4]['name']="body";
$z[7]=Array("prenext","",1909,1937);
$z[7][4]['get']="preimg";
$z[8]=Array("prenext","",1943,1972);
$z[8][4]['get']="nextimg";
$z[9]=Array("type","<a href=\"list.php?tid=[field:id/]\" title=\"返回列表\" class=\"back\">返回列表</a>",1978,2103);
$z[9][4]['typeid']="0";
$z[9][4]['row']="1";
$z[10]=Array("include","",2150,2189);
$z[10][4]['filename']="footer_m.htm";

?>