<?php
$z[0]=Array("field","",345,364);
$z[0][4]['name']="title";
$z[1]=Array("global","",365,391);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",987,1024);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1258,1287);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n        <li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span> </li>\r\n        ",1518,1732);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[5]=Array("field","",1829,1848);
$z[5][4]['name']="title";
$z[6]=Array("productimagelist","\r\n	  <center>\r\n        <img src=\"[field:imgsrc/]\" />\r\n      </center>\r\n	  <p style=\"height:10px\"></p>\r\n	  ",1858,2011);
$z[7]=Array("field","",2022,2040);
$z[7][4]['name']="body";
$z[8]=Array("prenext","",2065,2093);
$z[8][4]['get']="preimg";
$z[9]=Array("prenext","",2099,2128);
$z[9][4]['get']="nextimg";
$z[10]=Array("type","<a href=\"list.php?tid=[field:id/]\" title=\"返回列表\" class=\"back\">返回列表</a>",2134,2259);
$z[10][4]['typeid']="0";
$z[10][4]['row']="1";
$z[11]=Array("include","",2306,2345);
$z[11][4]['filename']="footer_m.htm";

?>