<?php
$z[0]=Array("field","",348,367);
$z[0][4]['name']="title";
$z[1]=Array("global","",368,394);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",990,1027);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1261,1290);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n        <li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span> </li>\r\n        ",1521,1735);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[5]=Array("field","",1832,1851);
$z[5][4]['name']="title";
$z[6]=Array("field","",1867,1885);
$z[6][4]['name']="body";
$z[7]=Array("prenext","",1910,1938);
$z[7][4]['get']="preimg";
$z[8]=Array("prenext","",1944,1973);
$z[8][4]['get']="nextimg";
$z[9]=Array("type","<a href=\"list.php?tid=[field:id/]\" title=\"返回列表\" class=\"back\">返回列表</a>",1979,2104);
$z[9][4]['typeid']="0";
$z[9][4]['row']="1";
$z[10]=Array("include","",2151,2190);
$z[10][4]['filename']="footer_m.htm";

?>