<?php
$z[0]=Array("field","",301,320);
$z[0][4]['name']="title";
$z[1]=Array("global","",321,347);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1495,1530);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1759,1788);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n  <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a><span>|</span>\r\n  ",1883,2036);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[5]=Array("field","",2110,2129);
$z[5][4]['name']="title";
$z[6]=Array("field","",2162,2214);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('Y/m/d',@me)";
$z[7]=Array("field","",2242,2269);
$z[7][4]['name']="phpurl";
$z[8]=Array("field","",2293,2316);
$z[8][4]['name']="id";
$z[9]=Array("field","",2321,2345);
$z[9][4]['name']="mid";
$z[10]=Array("field","",2456,2474);
$z[10][4]['name']="body";
$z[11]=Array("prenext","",2583,2608);
$z[11][4]['get']="pre";
$z[12]=Array("prenext","",2635,2661);
$z[12][4]['get']="next";
$z[13]=Array("type","<a href=\"[field:typelink /]\" title=\"返回列表\" class=\"back\">[返回列表]</a>",2673,2794);
$z[13][4]['typeid']="0";
$z[13][4]['row']="1";
$z[14]=Array("include","",2821,2858);
$z[14][4]['filename']="footer.htm";

?>