<?php
$z[0]=Array("field","",298,317);
$z[0][4]['name']="title";
$z[1]=Array("global","",318,344);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1492,1527);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1756,1785);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n  <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a><span>|</span>\r\n  ",1880,2033);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[5]=Array("field","",2107,2126);
$z[5][4]['name']="title";
$z[6]=Array("field","",2159,2211);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('Y/m/d',@me)";
$z[7]=Array("field","",2239,2266);
$z[7][4]['name']="phpurl";
$z[8]=Array("field","",2290,2313);
$z[8][4]['name']="id";
$z[9]=Array("field","",2318,2342);
$z[9][4]['name']="mid";
$z[10]=Array("productimagelist","\r\n	  <center><img src=\"[field:imgsrc/]\" alt=\"[field:text/]\" width=\"1000\" /></center>\r\n	  ",2458,2594);
$z[11]=Array("prenext","",2703,2728);
$z[11][4]['get']="pre";
$z[12]=Array("prenext","",2755,2781);
$z[12][4]['get']="next";
$z[13]=Array("type","<a href=\"[field:typelink /]\" title=\"返回列表\" class=\"back\">[返回列表]</a>",2793,2914);
$z[13][4]['typeid']="0";
$z[13][4]['row']="1";
$z[14]=Array("include","",2941,2978);
$z[14][4]['filename']="footer.htm";

?>