<?php
$z[0]=Array("flink"," [field:link /] ",80,167);
$z[0][4]['row']="24";
$z[0][4]['type']="text";
$z[0][4]['titlelen']="24";
$z[0][4]['typeid']="0";
$z[1]=Array("global","",226,252);
$z[1][4]['name']="cfg_dianhua";
$z[2]=Array("global","",274,298);
$z[2][4]['name']="cfg_dizhi";
$z[3]=Array("global","",325,351);
$z[3][4]['name']="cfg_banquan";
$z[4]=Array("global","",429,453);
$z[4][4]['name']="cfg_beian";

?>