<?php
$z[0]=Array("field","",301,320);
$z[0][4]['name']="title";
$z[1]=Array("global","",321,347);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1495,1530);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1762,1791);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n  <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a><span>|</span>\r\n  ",1886,2039);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[5]=Array("field","",2136,2157);
$z[5][4]['name']="content";
$z[6]=Array("include","",2223,2260);
$z[6][4]['filename']="footer.htm";

?>