<?php
$z[0]=Array("field","",345,364);
$z[0][4]['name']="title";
$z[1]=Array("global","",365,391);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1056,1093);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1319,1348);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n		  <li>\r\n                <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a>\r\n                <span class=\"commonfont class-down\">&#xe60c;</span>\r\n            </li>\r\n			",1569,1821);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[5]=Array("field","",1963,1984);
$z[5][4]['name']="content";
$z[6]=Array("include","",2037,2076);
$z[6][4]['filename']="footer_m.htm";

?>