<?php
$z[0]=Array("global","",415,441);
$z[0][4]['name']="cfg_dianhua";
$z[1]=Array("field","(@me==\"\")? @me=\"   class='cur'  \":@me=\"\";",507,598);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channel","\r\n	  <li class=\"nav2\"><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n	  ",663,905);
$z[2][4]['row']="10";
$z[2][4]['type']="top";
$z[2][4]['col']="1";
$z[2][4]['currentstyle']="<li><a class='cur' href='~typelink~' ~rel~>~typename~</a></li>";
$z[3]=Array("global","",1062,1087);
$z[3][4]['name']="cfg_cmsurl";

?>