<?php
$z[0]=Array("field","",345,364);
$z[0][4]['name']="title";
$z[1]=Array("global","",365,391);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",987,1024);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1252,1281);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1419,1440);
$z[4][4]['name']="content";
$z[5]=Array("include","",1492,1531);
$z[5][4]['filename']="footer_m.htm";

?>