<?php
$z[0]=Array("field","",348,367);
$z[0][4]['name']="title";
$z[1]=Array("global","",368,394);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",990,1027);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1255,1284);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n        <li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span> </li>\r\n        ",1515,1729);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[5]=Array("list","\r\n	  <li class=\"news4\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\"> <span>[field:title/]</span> </a> </li>\r\n	  ",1844,2057);
$z[5][4]['pagesize']="10";
$z[6]=Array("pagelist","",2108,2167);
$z[6][4]['istitem']="index,pre,next,end,";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2202,2241);
$z[7][4]['filename']="footer_m.htm";

?>