<?php
$z[0]=Array("field","",298,317);
$z[0][4]['name']="title";
$z[1]=Array("global","",318,344);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1492,1527);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1763,1792);
$z[3][4]['name']="typename";
$z[4]=Array("list","\r\n  <div class=\"hrBox\">\r\n    <div class=\"hrBoxL\">\r\n      <ul>\r\n        <li><span>所需职位：</span></li>\r\n        <li class=\"bgWhite\">所需人数：</li>\r\n        <li class=\"haode\">具体要求：</li>\r\n      </ul>\r\n      <div class=\"clear\"></div>\r\n    </div>\r\n    <div class=\"hrBoxR\">\r\n      <ul>\r\n        <li class=\"topline\"><span class=\"fl\">[field:title/]</span><a href=\"http://wpa.qq.com/msgrd?v=3&uin=6009709&site=qq&menu=yes\" class=\"fr\" title=\"应聘此职位\"><img src=\"/skin/images/re.gif\" width=\"90\" height=\"26\" /></a>\r\n          <div class=\"clear\"></div>\r\n        </li>\r\n        <li class=\"bgWhite\">[field:renshu/]\r\n          <div class=\"clear\"></div>\r\n        </li>\r\n        <li class=\"haode\">\r\n		[field:body/]\r\n		</li>\r\n      </ul>\r\n      <div class=\"clear\"></div>\r\n    </div>\r\n  </div>\r\n  ",1964,2810);
$z[4][4]['pagesize']="3";
$z[5]=Array("pagelist","",2846,2905);
$z[5][4]['istitem']="index,pre,next,end,";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",2936,2973);
$z[6][4]['filename']="footer.htm";

?>