<?php
$z[0]=Array("field","",298,317);
$z[0][4]['name']="title";
$z[1]=Array("global","",318,344);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1492,1527);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1759,1788);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n  <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a><span>|</span>\r\n  ",1883,2036);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[5]=Array("list","\r\n	<li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" width=\"315\" height=\"236\" alt=\"[field:title/]\"/> </a>\r\n      <p><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></p>\r\n    </li>\r\n	",2106,2376);
$z[5][4]['pagesize']="6";
$z[6]=Array("include","",2395,2432);
$z[6][4]['filename']="footer.htm";

?>