<?php
$z[0]=Array("field","",298,317);
$z[0][4]['name']="title";
$z[1]=Array("global","",318,344);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1492,1527);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1756,1785);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n  <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a><span>|</span>\r\n  ",1880,2033);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[5]=Array("list","\r\n	<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n	",2100,2292);
$z[5][4]['pagesize']="9";
$z[5][4]['infolen']="150";
$z[6]=Array("pagelist","",2342,2401);
$z[6][4]['istitem']="index,pre,next,end,";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2432,2469);
$z[7][4]['filename']="footer.htm";

?>