<?php
$z[0]=Array("field","",348,367);
$z[0][4]['name']="title";
$z[1]=Array("global","",368,394);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",990,1027);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1255,1284);
$z[3][4]['name']="typename";
$z[4]=Array("list","\r\n	  <li class=\"news1\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><span>[field:title/]</span><span>[field:pubdate function=\"MyDate('Y/m/d',@me)\"/]</span></a> </li>\r\n	  ",1444,1678);
$z[4][4]['pagesize']="6";
$z[4][4]['infolen']="150";
$z[5]=Array("pagelist","",1736,1795);
$z[5][4]['istitem']="index,pre,next,end,";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",1855,1894);
$z[6][4]['filename']="footer_m.htm";

?>