<?php
$z[0]=Array("field","",298,317);
$z[0][4]['name']="title";
$z[1]=Array("global","",318,344);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1492,1527);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1761,1790);
$z[3][4]['name']="typename";
$z[4]=Array("list","\r\n	<li>\r\n      <div class=\"con1_img\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" width=\"249\" height=\"332\" alt=\"[field:title/]\"/> </a>\r\n        <div> <span class=\"zoom1\"></span>\r\n          <p><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></p>\r\n          <div>[field:infos/]... </div>\r\n        </div>\r\n      </div>\r\n    </li>\r\n	",1970,2403);
$z[4][4]['pagesize']="18";
$z[4][4]['infolen']="150";
$z[5]=Array("include","",2422,2459);
$z[5][4]['filename']="footer.htm";

?>