<?php
$z[0]=Array("field","",345,364);
$z[0][4]['name']="title";
$z[1]=Array("global","",365,391);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",987,1024);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1252,1281);
$z[3][4]['name']="typename";
$z[4]=Array("list","\r\n	  <li class=\"news1\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><span>[field:title/]</span><span>[field:pubdate function=\"MyDate('Y/m/d',@me)\"/]</span></a> </li>\r\n	  ",1441,1675);
$z[4][4]['pagesize']="6";
$z[4][4]['infolen']="150";
$z[5]=Array("pagelist","",1733,1792);
$z[5][4]['istitem']="index,pre,next,end,";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",1852,1891);
$z[6][4]['filename']="footer_m.htm";

?>