<?php
$z[0]=Array("field","",345,364);
$z[0][4]['name']="title";
$z[1]=Array("global","",365,391);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",987,1024);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("field","",1252,1281);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n        <li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span> </li>\r\n        ",1512,1726);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[5]=Array("list","\r\n	  <li class=\"news4\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\"> <span>[field:title/]</span> </a> </li>\r\n	  ",1841,2053);
$z[5][4]['pagesize']="6";
$z[6]=Array("pagelist","",2104,2163);
$z[6][4]['istitem']="index,pre,next,end,";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2198,2237);
$z[7][4]['filename']="footer_m.htm";

?>