<?php
$z[0]=Array("field","",301,320);
$z[0][4]['name']="title";
$z[1]=Array("global","",321,347);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1495,1530);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1759,1788);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n  <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a><span>|</span>\r\n  ",1883,2036);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[5]=Array("list","\r\n	<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n	",2103,2295);
$z[5][4]['pagesize']="9";
$z[5][4]['infolen']="150";
$z[6]=Array("pagelist","",2345,2404);
$z[6][4]['istitem']="index,pre,next,end,";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2435,2472);
$z[7][4]['filename']="footer.htm";

?>