<?php
$z[0]=Array("field","",301,320);
$z[0][4]['name']="title";
$z[1]=Array("global","",321,347);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1495,1530);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1759,1788);
$z[3][4]['name']="typename";
$z[4]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a><span>|</span> ",1880,2027);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[5]=Array("list","\r\n    <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" width=\"315\" height=\"236\" alt=\"[field:title/]\"/> </a>\r\n      <p><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></p>\r\n    </li>\r\n    ",2093,2369);
$z[5][4]['pagesize']="6";
$z[6]=Array("pagelist","",2419,2478);
$z[6][4]['istitem']="index,pre,next,end,";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2509,2546);
$z[7][4]['filename']="footer.htm";

?>