<?php
$z[0]=Array("global","",305,331);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",1479,1514);
$z[1][4]['filename']="head.htm";
$z[2]=Array("list","\r\n	<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n	",1941,2133);
$z[2][4]['pagesize']="9";
$z[2][4]['infolen']="150";
$z[3]=Array("pagelist","",2183,2242);
$z[3][4]['istitem']="index,pre,next,end,";
$z[3][4]['listsize']="5";
$z[4]=Array("include","",2273,2310);
$z[4][4]['filename']="footer.htm";

?>